"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-07

The whole schema in one revision: the append-only `events` ledger, the four
effective-dated definition version tables, and `receipt_blobs`.

Generated by `alembic revision --autogenerate` against `persistence.base.Base.metadata`
and left as generated apart from this docstring and the `persistence.base` import that
autogenerate omits — a hand-edited migration that drifts from the models is the failure
this one is deliberately not risking. `alembic check` against a freshly-upgraded
database reports no difference; that is the assertion, and
`tests/unit/persistence/test_migrations.py` re-runs it rather than trusting it.

`downgrade()` drops the tables it created. That is not a violation of CLAUDE.md §4.3 —
the prohibition there is on destroying ledger rows as a way of correcting them, and
these statements only ever run to unwind a migration that has just been applied to a
schema that did not previously exist. No application code path can reach them.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import persistence.base

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('kind', sa.Enum('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'LOAN', name='account_kind', native_enum=False, length=16), nullable=False),
    sa.Column('apr_bps', sa.Integer(), nullable=False),
    sa.Column('statement_close_day', sa.Integer(), nullable=True),
    sa.Column('payment_due_day', sa.Integer(), nullable=True),
    sa.Column('budget_timing', sa.Enum('AT_PURCHASE', 'AT_STATEMENT_PAYMENT', name='budget_timing', native_enum=False, length=24), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', persistence.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("budget_timing IN ('AT_PURCHASE', 'AT_STATEMENT_PAYMENT')", name=op.f('ck_accounts_budget_timing_values')),
    sa.CheckConstraint("kind IN ('CHECKING', 'SAVINGS', 'CREDIT_CARD', 'LOAN')", name=op.f('ck_accounts_kind_values')),
    sa.CheckConstraint('apr_bps >= 0', name=op.f('ck_accounts_apr_bps_non_negative')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_accounts_effective_range')),
    sa.CheckConstraint('payment_due_day IS NULL OR payment_due_day BETWEEN 1 AND 31', name=op.f('ck_accounts_payment_due_day_range')),
    sa.CheckConstraint('statement_close_day IS NULL OR statement_close_day BETWEEN 1 AND 31', name=op.f('ck_accounts_statement_close_day_range')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('entity_id', 'effective_from', name=op.f('uq_accounts_entity_id_effective_from'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index('ix_accounts_entity_id_effective_from', ['entity_id', 'effective_from'], unique=False)
        batch_op.create_index('uq_accounts_open_version', ['entity_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    op.create_table('allocation_policies',
    sa.Column('savings_bps', sa.Integer(), nullable=False),
    sa.Column('discretionary_bps', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', persistence.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_allocation_policies_effective_range')),
    sa.CheckConstraint('savings_bps + discretionary_bps = 10000', name=op.f('ck_allocation_policies_bps_total_10000')),
    sa.CheckConstraint('savings_bps >= 0 AND discretionary_bps >= 0', name=op.f('ck_allocation_policies_bps_non_negative')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_allocation_policies')),
    sa.UniqueConstraint('entity_id', 'effective_from', name=op.f('uq_allocation_policies_entity_id_effective_from'))
    )
    with op.batch_alter_table('allocation_policies', schema=None) as batch_op:
        batch_op.create_index('ix_allocation_policies_entity_id_effective_from', ['entity_id', 'effective_from'], unique=False)
        batch_op.create_index('uq_allocation_policies_open_version', ['entity_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    op.create_table('fixed_costs',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('cadence', sa.Enum('WEEKLY', 'BIWEEKLY', 'SEMIMONTHLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='cadence', native_enum=False, length=16), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('payee', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', persistence.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("cadence IN ('WEEKLY', 'BIWEEKLY', 'SEMIMONTHLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL')", name=op.f('ck_fixed_costs_cadence_values')),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name=op.f('ck_fixed_costs_due_day_range')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_fixed_costs_effective_range')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_fixed_costs')),
    sa.UniqueConstraint('entity_id', 'effective_from', name=op.f('uq_fixed_costs_entity_id_effective_from'))
    )
    with op.batch_alter_table('fixed_costs', schema=None) as batch_op:
        batch_op.create_index('ix_fixed_costs_entity_id_effective_from', ['entity_id', 'effective_from'], unique=False)
        batch_op.create_index('uq_fixed_costs_open_version', ['entity_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    op.create_table('receipt_blobs',
    sa.Column('blob_id', sa.String(length=36), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.CheckConstraint('byte_size >= 0', name=op.f('ck_receipt_blobs_byte_size_non_negative')),
    sa.PrimaryKeyConstraint('blob_id', name=op.f('pk_receipt_blobs')),
    sa.UniqueConstraint('content_sha256', name=op.f('uq_receipt_blobs_content_sha256'))
    )
    op.create_table('recurring_incomes',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('cadence', sa.Enum('WEEKLY', 'BIWEEKLY', 'SEMIMONTHLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL', name='cadence', native_enum=False, length=16), nullable=False),
    sa.Column('anchor_day', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=128), nullable=False),
    sa.Column('version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('recorded_at', persistence.base.UtcDateTime(timezone=True), nullable=False),
    sa.CheckConstraint("cadence IN ('WEEKLY', 'BIWEEKLY', 'SEMIMONTHLY', 'MONTHLY', 'QUARTERLY', 'ANNUAL')", name=op.f('ck_recurring_incomes_cadence_values')),
    sa.CheckConstraint('anchor_day BETWEEN 1 AND 31', name=op.f('ck_recurring_incomes_anchor_day_range')),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_recurring_incomes_effective_range')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_recurring_incomes')),
    sa.UniqueConstraint('entity_id', 'effective_from', name=op.f('uq_recurring_incomes_entity_id_effective_from'))
    )
    with op.batch_alter_table('recurring_incomes', schema=None) as batch_op:
        batch_op.create_index('ix_recurring_incomes_entity_id_effective_from', ['entity_id', 'effective_from'], unique=False)
        batch_op.create_index('uq_recurring_incomes_open_version', ['entity_id'], unique=True, sqlite_where=sa.text('effective_to IS NULL'), postgresql_where=sa.text('effective_to IS NULL'))

    op.create_table('events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('recorded_at', persistence.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('dedupe_key', sa.String(length=512), nullable=False),
    sa.Column('note', sa.String(length=1024), nullable=True),
    sa.Column('external_ref_provider', sa.String(length=64), nullable=True),
    sa.Column('external_ref_provider_txn_id', sa.String(length=256), nullable=True),
    sa.Column('amount_minor', sa.BigInteger(), nullable=True),
    sa.Column('principal_minor', sa.BigInteger(), nullable=True),
    sa.Column('interest_minor', sa.BigInteger(), nullable=True),
    sa.Column('account_id', sa.String(length=128), nullable=True),
    sa.Column('from_account_id', sa.String(length=128), nullable=True),
    sa.Column('to_account_id', sa.String(length=128), nullable=True),
    sa.Column('obligation_id', sa.String(length=128), nullable=True),
    sa.Column('recurring_id', sa.String(length=128), nullable=True),
    sa.Column('cycle_id', sa.String(length=160), nullable=True),
    sa.Column('target_event_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('payee', sa.String(length=256), nullable=True),
    sa.Column('merchant', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=256), nullable=True),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('receipt_blob_id', sa.String(length=36), nullable=True),
    sa.CheckConstraint('(external_ref_provider IS NULL) = (external_ref_provider_txn_id IS NULL)', name=op.f('ck_events_external_ref_complete')),
    sa.ForeignKeyConstraint(['receipt_blob_id'], ['receipt_blobs.blob_id'], name=op.f('fk_events_receipt_blob_id_receipt_blobs')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_events_dedupe_key'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_account_id', ['account_id'], unique=False)
        batch_op.create_index('ix_events_category', ['category'], unique=False)
        batch_op.create_index('ix_events_event_type', ['event_type'], unique=False)
        batch_op.create_index('ix_events_ledger_order', ['event_date', 'recorded_at', 'event_id'], unique=False)
        batch_op.create_index('ix_events_target_event_id', ['target_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Refuse. This migration is not reversible.

    CLAUDE.md §4.3 is unconditional: there is no DELETE in this codebase, no `DROP`, no
    `TRUNCATE`. Autogenerate wrote the mirror image of `upgrade()` here — nineteen
    statements removing every index and every table, `events` among them. Running it
    would destroy the entire append-only ledger irrecoverably, which is the precise loss
    §4.3 exists to prevent. Generated scaffolding is not an exemption; this file is
    checked in, so it is code in this codebase.

    Raising is the conventional way to declare an irreversible migration, and it is the
    honest one. `pass` would be worse than the statements it replaced: Alembic would
    report a successful downgrade having done nothing, and the schema would silently
    disagree with the version table.

    There is nothing to reverse in practice. This is the initial revision, so the only
    database it could run against is one whose entire schema this migration created —
    and a database with a ledger in it is never that database again. Recovering from a
    bad migration is a restore from backup, not a downgrade.

    `tests/unit/persistence/test_no_hard_deletes.py` enforces both halves of this: that
    no destructive call or raw statement appears anywhere under `alembic/`, and that
    `downgrade()` refuses rather than silently doing nothing.
    """
    raise NotImplementedError(
        "0001_initial is irreversible by design (CLAUDE.md §4.3): reversing it would "
        "remove the events table and destroy the append-only ledger. Restore from a "
        "backup instead."
    )
