"""There is no DELETE in this codebase, and exactly one UPDATE.

CLAUDE.md §4.3 is a rule about code that does not exist yet as much as about code that
does. A reviewer can check it once; this test checks it on every run, by parsing to an
AST rather than reading — the same reasoning as `tools/check_domain_purity.py`, so a
docstring may say "no DELETE" and a comment may contain the word without tripping
anything.

The purity gate itself covers `core/` and `domain/` only. This suite covers the two
directories that can actually break §4.3: `persistence/` and **`alembic/`**.

Alembic is included because of a real miss. This test originally scanned `persistence/`
alone, and the only `DROP` in the entire repository was sitting in the one directory it
did not look at — the autogenerated `downgrade()` of the initial migration, which
dropped `events` and every other table. Autogenerated scaffolding is not an exemption:
the file is checked in, so it is code in this codebase. A rule enforced over the
directory where it is easy to keep, and not over the directory where it was already
broken, is not enforcement.
"""

from __future__ import annotations

import ast
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
PERSISTENCE = REPO_ROOT / "persistence"
ALEMBIC = REPO_ROOT / "alembic"

#: Destructive SQL, matched against string literals passed to a call (`op.execute(...)`,
#: `text(...)`). Anchored on a following keyword so that prose like "dropping the events
#: table" in a message argument is not a false positive, while `DROP TABLE events` is.
DESTRUCTIVE_SQL = re.compile(
    r"\b(DELETE\s+FROM|DROP\s+(TABLE|INDEX|CONSTRAINT|SCHEMA|DATABASE)|TRUNCATE)\b"
)


def _called_names(tree: ast.AST) -> list[str]:
    """Every callee name in the module, as written.

    `f(...)` yields `f`; `a.b.f(...)` yields `f`. Attribute chains are reduced to the
    final attribute so that `session.delete(...)` and `delete(...)` are both caught.
    """
    names: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if isinstance(func, ast.Name):
            names.append(func.id)
        elif isinstance(func, ast.Attribute):
            names.append(func.attr)
    return names


def _bare_called_names(tree: ast.AST) -> list[str]:
    """Callees written as a plain name — `f(...)`, never `x.f(...)`.

    The distinction matters for exactly one word. `sqlalchemy.update` is imported as a
    name and called bare, while `dict.update` is only ever reached through an
    attribute; counting both would flag every `values.update(...)` in the mapping layer
    as a mutation of the database.
    """
    return [
        node.func.id
        for node in ast.walk(tree)
        if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)
    ]


def _call_string_arguments(tree: ast.AST) -> list[str]:
    """String literals passed as arguments to a call.

    Deliberately not "every string literal in the module": a docstring stating the rule
    ("no `DROP TABLE`") is an `ast.Expr`, not a call argument, so it is invisible here.
    That is the same distinction `tools/check_domain_purity.py` draws, and it is what
    lets this test coexist with documentation that quotes the SQL it forbids.
    """
    literals: list[str] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        for argument in [*node.args, *(kw.value for kw in node.keywords)]:
            if isinstance(argument, ast.Constant) and isinstance(argument.value, str):
                literals.append(argument.value)
    return literals


def _parse(directory: Path) -> list[tuple[Path, ast.Module]]:
    return [
        (path, ast.parse(path.read_text(encoding="utf-8"), filename=str(path)))
        for path in sorted(directory.rglob("*.py"))
        if "__pycache__" not in path.parts
    ]


def _modules() -> list[tuple[Path, ast.Module]]:
    """`persistence/` only — the scope of the UPDATE and import-direction rules."""
    return _parse(PERSISTENCE)


def _scanned_modules() -> list[tuple[Path, ast.Module]]:
    """`persistence/` and `alembic/` — everything that can issue destructive SQL."""
    return _parse(PERSISTENCE) + _parse(ALEMBIC)


def test_nothing_deletes_or_drops() -> None:
    """No `delete(...)`, `session.delete(...)`, `drop_table(...)`, `truncate(...)`.

    Corrections are `EventVoided` rows and definition changes are new versions
    (PLAN.md §8.4). Nothing in either directory needs to remove a row or a table, so
    nothing may — including a migration's `downgrade()`, which is exactly where this
    rule got broken once already.
    """
    forbidden = {
        "delete",
        "drop",
        "drop_all",
        "truncate",
        "drop_table",
        "drop_index",
        "drop_constraint",
        "drop_column",
        "drop_schema",
        "execute_ddl",
    }
    offenders = [
        (str(path.relative_to(REPO_ROOT)), name)
        for path, tree in _scanned_modules()
        for name in _called_names(tree)
        if name in forbidden
    ]
    assert offenders == []


def test_no_destructive_raw_sql() -> None:
    """The same rule, for SQL that never becomes an AST call of its own.

    `op.execute("DROP TABLE events")` and `session.execute(text("DELETE FROM events"))`
    both slip past a callee-name check — the destructive verb is inside a string. This
    is the second door, and it is the one a hand-written migration would use.
    """
    offenders = [
        (str(path.relative_to(REPO_ROOT)), literal)
        for path, tree in _scanned_modules()
        for literal in _call_string_arguments(tree)
        if DESTRUCTIVE_SQL.search(literal.upper())
    ]
    assert offenders == []


def test_the_migration_downgrade_refuses_rather_than_dropping() -> None:
    """`downgrade()` is an explicit refusal, not an empty body.

    A `pass` would satisfy the two tests above while quietly claiming the migration is
    reversible, and Alembic would report success having done nothing. Raising is the
    conventional way to declare an irreversible migration, and it is the honest one:
    this schema cannot be reversed because reversing it would destroy the ledger.
    """
    for path, tree in _parse(ALEMBIC / "versions"):
        downgrades = [
            node
            for node in ast.walk(tree)
            if isinstance(node, ast.FunctionDef) and node.name == "downgrade"
        ]
        assert downgrades, f"{path.name} has no downgrade()"
        for node in downgrades:
            raised = [child for child in ast.walk(node) if isinstance(child, ast.Raise)]
            assert raised, f"{path.name}: downgrade() does not refuse"


def test_persistence_issues_exactly_one_update() -> None:
    """One `update(` call, and it is `close_version`'s.

    "Closing a version is the single permitted UPDATE" is only checkable if there is
    exactly one place it could happen. This is that check; if a second `update(` ever
    appears, this test names the file it appeared in.
    """
    updates = [
        path.name
        for path, tree in _modules()
        for name in _bare_called_names(tree)
        if name == "update"
    ]
    assert updates == ["repositories.py"]


def test_the_only_update_lives_in_close_version() -> None:
    """Located precisely, not merely counted.

    A single `update(` in the right file but the wrong function would pass the count
    above and still violate §4.3.
    """
    tree = ast.parse((PERSISTENCE / "repositories.py").read_text(encoding="utf-8"))
    hosting_functions = [
        node.name
        for node in ast.walk(tree)
        if isinstance(node, ast.FunctionDef)
        for name in _bare_called_names(node)
        if name == "update"
    ]
    assert hosting_functions == ["close_version"]


def test_no_ddl_is_emitted_from_the_repositories() -> None:
    """Schema changes belong to Alembic. A repository that could `create_all` could,
    with one more line, `drop_all`."""
    tree = ast.parse((PERSISTENCE / "repositories.py").read_text(encoding="utf-8"))
    assert "create_all" not in _called_names(tree)


def test_persistence_never_imports_upward() -> None:
    """Dependencies point strictly upward (CLAUDE.md §3.1).

    `persistence/` may import `core/` and `domain/`. Importing `api/` or `ingestion/`
    would make the graph cyclic, and a cycle is a build failure rather than a style
    issue.
    """
    forbidden_roots = {"api", "ingestion"}
    offenders: list[tuple[str, str]] = []
    for path, tree in _modules():
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name.split(".")[0] in forbidden_roots:
                        offenders.append((path.name, alias.name))
            elif isinstance(node, ast.ImportFrom) and node.module is not None:
                if node.module.split(".")[0] in forbidden_roots:
                    offenders.append((path.name, node.module))
    assert offenders == []


def test_no_float_or_decimal_column_types() -> None:
    """Money is `int` minor units everywhere (CLAUDE.md §2.1).

    The purity gate does not reach `persistence/`, and a `Float` or `Numeric` column is
    exactly the way a float would get in without any float literal ever appearing in the
    source.
    """
    forbidden = {"Float", "Numeric", "REAL", "DECIMAL", "Decimal"}
    offenders = [
        (path.name, name)
        for path, tree in _modules()
        for node in ast.walk(tree)
        if isinstance(node, ast.Name)
        for name in [node.id]
        if name in forbidden
    ]
    assert offenders == []
